# Generated by Django 4.1.13 on 2024-05-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conseiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUtilisateur', models.CharField(max_length=100)),
                ('motDePasse', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('Instagram', models.CharField(max_length=100)),
                ('Linkedin', models.CharField(max_length=100)),
                ('Gmail', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Conseillers',
            },
        ),
    ]
