# Generated by Django 5.0.6 on 2024-05-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='advise_id',
            new_name='advise',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='student_id',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
