# Generated by Django 4.1.13 on 2024-05-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_notification_conseiller_delete_post_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
