# Generated by Django 4.1.13 on 2024-05-08 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_delete_article_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conseiller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.conseiller')),
            ],
            options={
                'db_table': 'Notifications',
            },
        ),
    ]
