# Generated by Django 4.1.13 on 2024-05-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='etat',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Acceptée', 'Acceptée'), ('Refusée', 'Refusée')], default='En attente', max_length=20),
        ),
    ]
