# Generated by Django 4.1.13 on 2024-05-09 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_demande_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.etudiant')),
            ],
            options={
                'db_table': 'Notifications_Etudiant',
            },
        ),
    ]
