# Generated by Django 5.0.6 on 2024-05-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_admin_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RemoveField(
            model_name='media',
            name='image_url',
        ),
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='file_path',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
