# Generated by Django 5.0.6 on 2024-05-19 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_event_id_media_event_remove_media_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='description',
        ),
    ]
