# Generated by Django 5.0.6 on 2024-05-21 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_notification_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='shared',
        ),
        migrations.AddField(
            model_name='feedback',
            name='advise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.advise'),
            preserve_default=False,
        ),
    ]
