# Generated by Django 5.0.6 on 2024-05-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_remove_feedback_shared_feedback_advise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='student_id',
            new_name='student',
        ),
    ]
