# Generated by Django 5.0.6 on 2024-05-22 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_user_is_active'),
        ('website', '0021_record_appointment'),
    ]

    operations = [
    ]
