# Generated by Django 5.0.6 on 2024-05-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_merge_20240522_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='date',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='time',
        ),
        migrations.AddField(
            model_name='calendar',
            name='availability',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
