# Generated by Django 5.0.6 on 2024-05-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_remove_calendar_date_remove_calendar_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='file_path',
            new_name='image_path',
        ),
    ]
