# Generated by Django 5.0.6 on 2024-05-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_rename_file_path_media_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='advise_id',
            new_name='advise',
        ),
    ]
